// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.javascript.options.wasm_caching", false);
user_pref("app.normandy.user_id", "8f10958f-58bc-478b-8063-d409aa06ab94");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1676268144);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1676268116);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1676268115);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{67bbe1fa-e4e9-45ec-9bb1-c6a17aca9fcf}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1649096832);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c97882ad-5b68-4f84-9b17-5f032edd2c90}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1649096834);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1676268117250");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1676289717250");
user_pref("browser.search.region", "OM");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230127170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1650517751");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230127170202");
user_pref("browser.startup.homepage_override.mstone", "109.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1676268115);
user_pref("browser.startup.upgradeDialog.version", 106);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1650517761371");
user_pref("disableResetPrompt", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "109.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "OM");
user_pref("dom.push.userAgentID", "43081876805246ca82eb4f4ccdd74089");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1676268115);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230127170202");
user_pref("extensions.lastAppVersion", "109.0.1");
user_pref("extensions.lastPlatformVersion", "109.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.plugin.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a3cdb45a-115d-425d-bb56-ecdd2c9dd22b\",\"formautofill@mozilla.org\":\"636adb2f-4222-4d29-b9e0-bed221d4dcaf\",\"pictureinpicture@mozilla.org\":\"7018f3ec-8482-4040-8b52-80d3d63329dc\",\"screenshots@mozilla.org\":\"78ca7150-fc2b-4e26-9792-3ac3736ceb25\",\"webcompat-reporter@mozilla.org\":\"913da858-c280-40f3-b896-fb1a40fa2a1d\",\"webcompat@mozilla.org\":\"c55ae6cf-41a6-449e-8f80-9066d7fb3365\",\"default-theme@mozilla.org\":\"ddd7ddf2-b929-4ed3-a052-6bd129390357\",\"addons-search-detection@mozilla.com\":\"89b2a53f-12ef-45b1-b78d-8e2969b199dc\",\"google@search.mozilla.org\":\"ddd5617c-ddae-4e0c-b6a5-f041e0f4aadf\",\"amazondotcom@search.mozilla.org\":\"ec6491c7-7322-4521-9c2a-88971b52c120\",\"wikipedia@search.mozilla.org\":\"94a7f293-e2ec-49ac-82c2-185d6554b520\",\"bing@search.mozilla.org\":\"71ef9888-e3db-4b65-bbfb-164141adb01f\",\"ddg@search.mozilla.org\":\"6fb427eb-c903-4677-a6a3-b28ab6d09e3a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastDownload", 1676268126);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1676268125);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1676268126);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "726695e8-6572-429c-9deb-f6e63347342d");
user_pref("toolkit.startup.last_success", 1676268113);
user_pref("toolkit.telemetry.cachedClientID", "566b8117-0f49-44f0-9e40-5cf27984bfec");
user_pref("toolkit.telemetry.previousBuildID", "20230127170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
